version: '3.9'

services:
  mongodb:
    image: mongo:8
    restart: always
    container_name: mongodb-eiei
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
